<a href="https://colab.research.google.com/github/MinyoungHer/Pytorch-study/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


#00. Pytorch Fundamentals




In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


##Introduction to Tensors

### Creating Tensor

Pytorch tensors are created using torch.Tensor()

In [ ]:
# scalar
scalar=torch.tensor(7)

In [ ]:
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#Get tensor back as Python int
scalar.item()

7

In [ ]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#Matrix
matrix=torch.tensor([[7,8],
                     [9,10]])

In [ ]:
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
matrix.ndim

2

In [ ]:
matrix[:,1]

tensor([ 8, 10])

In [ ]:
matrix.shape

torch.Size([2, 2])

In [ ]:
#Tensor
tensor=torch.tensor([[[1,2,3],
                      [3,6,9],
                     [2,4,5]]])
tensor


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [ ]:
tensor.ndim

3

In [ ]:
tensor.shape
#1 3X3 tensor

torch.Size([1, 3, 3])

In [ ]:
tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

### Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

'start with random numbers --> look at data --> update random numbers --> look at data --> update random numbers

In [ ]:
# Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.0523, 0.0576, 0.1783, 0.3436],
        [0.7528, 0.6121, 0.3613, 0.4081],
        [0.6591, 0.0063, 0.4412, 0.2233]])

In [ ]:
random_tensor.ndim

2

In [ ]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) #height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(size=(3,3))

tensor([[0.6720, 0.3592, 0.7793],
        [0.6138, 0.2114, 0.6060],
        [0.9046, 0.8501, 0.7956]])

### zeros and ones

In [ ]:
#create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# create a tensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### creating a range of tensors and tensors_like

In [ ]:
#use torch.range()
torch.arange(0,10)
one_to_ten=torch.arange(start=1,end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note**: Tensor datatype is one of the 3 big errors you'll run into with Pytorch $ deep learning:
1. Tensors not right datatype(some operation)
2. Tensors not right shape
3. Tensors not on the rigth device


Precision in computer science

In [ ]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None, #What datatype is the tensor
                             device=None, #What device is your tensor on
                             requires_grad=False) # Whether or not to track gradients with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_16_tensor=float_32_tensor.type(torch.float16)

In [ ]:
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [ ]:
int_32_tensor=torch.tensor([3,6,9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor

tensor([3., 6., 9.])

### Getting information from tensors attributes
1. Tensors not right datatype(some operation)- to do get datatype from a tensor, can use 'tensor.dtype'
2. Tensors not right shape- to get shape from a tensor, can use 'tensor.shape'
3. Tensors not on the rigth device- tod get device from a tensor, can use 'tensor.device'


In [ ]:
#create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.1081, 0.6798, 0.2077, 0.3300],
        [0.2457, 0.9778, 0.7410, 0.4760],
        [0.6996, 0.7613, 0.2889, 0.6490]])

In [ ]:
#find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.1081, 0.6798, 0.2077, 0.3300],
        [0.2457, 0.9778, 0.7410, 0.4760],
        [0.6996, 0.7613, 0.2889, 0.6490]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (elemnet_wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it

tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor=tensor*10

In [ ]:
tensor

tensor([10, 20, 30])

In [ ]:
#substract 10
tensor-10

tensor([ 0, 10, 20])

In [ ]:
# Try out pytorch in-built functions
torch.mul(tensor, 10)

tensor([100, 200, 300])

In [ ]:
torch.mul(tensor, tensor)

tensor([100, 400, 900])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* '(3,2)@(3,2) won't work
* '(2,3)@(3,2) will work
2. The resulting matrix has the shape of the **outer dimensions**:


In [ ]:
# Elemnet wise multimplication
print(tensor,'*',tensor)
print(f"equals: {tensor*tensor}")

tensor([10, 20, 30]) * tensor([10, 20, 30])
equals: tensor([100, 400, 900])


In [ ]:
#Matrix multiplication
torch.matmul(tensor, tensor.T)

tensor(1400)

In [ ]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(1400)
CPU times: user 3.14 ms, sys: 0 ns, total: 3.14 ms
Wall time: 3.15 ms


In [ ]:
%%time
torch.matmul(tensor, tensor)
#much more faster

CPU times: user 74 µs, sys: 0 ns, total: 74 µs
Wall time: 78 µs


tensor(1400)

### One of the most common error in deep learning: shape errors

In [ ]:
# shapes for matrix multiplication
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_B=torch.tensor([[7,10],
                      [8,11],
                      [9,12]])
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [ ]:
#The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A={tensor_A.shape}, tensor_B={tensor_B.shape}")
print(f"New shapes: tensor_A={tensor_A.shape} (same shape as above), tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape}@{tensor_B.T.shape}<- inner dimensions must match")


torch.matmul(tensor_A, tensor_B.T)

Original shapes: tensor_A=torch.Size([3, 2]), tensor_B=torch.Size([3, 2])
New shapes: tensor_A=torch.Size([3, 2]) (same shape as above), tensor_B.T=torch.Size([2, 3])
Multiplying: torch.Size([3, 2])@torch.Size([2, 3])<- inner dimensions must match


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

## Finding the min, max, mean, sum , etc (tensor aggregation)

In [ ]:
#create a tensor
x=torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#Find the min
torch.max(x), x.min()

(tensor(91), tensor(1))

In [ ]:
#Find the mean- note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x.type(torch.float32)) , x.type(torch.float32).mean()

(tensor(46.), tensor(46.))

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max


In [ ]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [ ]:
#Find the position in tensor that has the minimum value with argmin() --> returns index position of target tensor where the minimum value occurs
x.argmin()

tensor(0)

In [ ]:
x[0]

tensor(1)

In [ ]:
x.argmax()

tensor(9)

In [ ]:
x[9]

tensor(91)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - reshapes an input tensor to a defined shape
* View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* squeeze - removes all '1' dimensions from a tensor
* unsqueeze - add a '1' dimension to a target tensor
* permute - return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
# creating tensor
import torch
x=torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Add an extra dimension
x_reshaped=x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#change the view
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
#changing z chages x (because a view of a tensor shares the same memory as the original input)
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked1=torch.stack([x,x,x,x])
x_stacked1

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.],
        [1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
#torch.squeeze()- removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimensions from x_shaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [ ]:
x_reshaped.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
x_reshaped.squeeze().shape

torch.Size([9])

In [ ]:
# torch.unsqueeze()- adds a single dimension to a target tesor at a specific dim
print(f"previous target: {x_squeezed}")
print(f'Previous shape: {x_squeezed.shape}')

#add an extra dimension with unsqueeze
x_unsqueezed=x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

previous target: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original=torch.rand(size=(224,224,3))
# permute the original tensor to rearrange the axis (or dim) order

x_permuted=x_original.permute(2,0,1)
print(x_original.size())
print(x_permuted.size())

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


In [ ]:
x_original[0,0,0]=72818
x_original[0,0,0], x_permuted[0,0,0]

(tensor(72818.), tensor(72818.))

## Indexing (selecting data from tensors)

Indexing with Pytorch is similar to indexing with Numpy

In [ ]:
# create a tensor
import torch
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# index on the middle barcket(dim=1)
x[0][0]
x[0,0]

tensor([1, 2, 3])

In [ ]:
# index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [ ]:
# also use ':' to select 'all' of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [ ]:
# get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 3,6,9
x[0,:,2]

tensor([3, 6, 9])

## Pytorch tensors & Numpy

Numpy is a popular scientific Python numerical computing library

And because of this, Pytorch has functionality to interact with it.

* Data in Numpy, want in Pytorch tensor -->
 'torch.from_numpy(ndarray)'
* Pytorch tensor -> numpy -->
 'torch.Tensor.numpy()'

In [ ]:
#Numpy array to tensor
import torch
import numpy as np

array=np.arange(1.0, 8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array, tensor

#Warning: when converting from numpy --> pytorch, pytorch reflects numpy's default of float64 unless specified otherwise

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
tensor.dtype


torch.float32

In [ ]:
#change the value of array, what will this do to 'tensor?
array=array+1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to Numpy
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
numpy_tensor.dtype

dtype('float32')

In [ ]:
#change the tensor, what happens to numpy_tensor?

tensor=tensor+1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility(trying to take random out of random)

In short how a neural network learns:

'start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data ---> again -> again...'

Tor reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**
Essentially what the random seed does is "flavour" the randomness

In [ ]:
import torch

#create two random tensors
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8268, 0.9454, 0.9091, 0.4734],
        [0.3975, 0.3050, 0.9940, 0.6166],
        [0.6622, 0.3623, 0.8139, 0.7198]])
tensor([[0.9142, 0.4300, 0.1171, 0.2422],
        [0.9554, 0.3730, 0.1625, 0.3997],
        [0.7981, 0.2803, 0.1034, 0.5958]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# random but reproducible tensors
import torch

#set the random seed
random_seed=42
torch.manual_seed(random_seed)

random_tensor_c=torch.rand(3,4)

torch.manual_seed(random_seed)
random_tensor_d=torch.rand(3,4)

print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c==random_tensor_d)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and pytorch objects on the GPUs (and making faster computations)

GPUs=faster computation on numbers, thanks to CUDA + NVIDIA hardware +Pytorch working behind the scenes to make everything good

### 1. Getting a GPU

1. easiest - use google colab for a free GPU (options to upgrade as well)
2. Use your own GPU
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2,3 Pytorch + GPU drivers (CUDA) takes a little bit of setting up

### 2. check for GPU access with Pytorch




In [ ]:
#check for GPU access with Pytorch

import torch
torch.cuda.is_available()

True

In [ ]:
#setup device agnostic code
device='cuda' if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
#count number of devices
torch.cuda.device_count()

1

## 3. putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is beacuse using a GPU results in faster computiations

In [ ]:
# create a tensor(default on the CPU)

tensor=torch.tensor([1,2,3])

#tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
#Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# if tensor is on GPU, can't transform it to NUMPY
tensor_on_gpu.numpy()

TypeError: ignored

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu=tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')